// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bilibili.proto

package dm // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DmSegMobileReply struct {
	Elems                []*DanmakuElem `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DmSegMobileReply) Reset()         { *m = DmSegMobileReply{} }
func (m *DmSegMobileReply) String() string { return proto.CompactTextString(m) }
func (*DmSegMobileReply) ProtoMessage()    {}
func (*DmSegMobileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bilibili_95d7436dab1fa0ff, []int{0}
}
func (m *DmSegMobileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DmSegMobileReply.Unmarshal(m, b)
}
func (m *DmSegMobileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DmSegMobileReply.Marshal(b, m, deterministic)
}
func (dst *DmSegMobileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DmSegMobileReply.Merge(dst, src)
}
func (m *DmSegMobileReply) XXX_Size() int {
	return xxx_messageInfo_DmSegMobileReply.Size(m)
}
func (m *DmSegMobileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DmSegMobileReply.DiscardUnknown(m)
}

var xxx_messageInfo_DmSegMobileReply proto.InternalMessageInfo

func (m *DmSegMobileReply) GetElems() []*DanmakuElem {
	if m != nil {
		return m.Elems
	}
	return nil
}

type DanmakuElem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Progress             int32    `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Mode                 int32    `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Fontsize             int32    `protobuf:"varint,4,opt,name=fontsize,proto3" json:"fontsize,omitempty"`
	Color                uint32   `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	MidHash              string   `protobuf:"bytes,6,opt,name=midHash,proto3" json:"midHash,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Ctime                int64    `protobuf:"varint,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Weight               int32    `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Action               string   `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	Pool                 int32    `protobuf:"varint,11,opt,name=pool,proto3" json:"pool,omitempty"`
	IdStr                string   `protobuf:"bytes,12,opt,name=idStr,proto3" json:"idStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmakuElem) Reset()         { *m = DanmakuElem{} }
func (m *DanmakuElem) String() string { return proto.CompactTextString(m) }
func (*DanmakuElem) ProtoMessage()    {}
func (*DanmakuElem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bilibili_95d7436dab1fa0ff, []int{1}
}
func (m *DanmakuElem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmakuElem.Unmarshal(m, b)
}
func (m *DanmakuElem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmakuElem.Marshal(b, m, deterministic)
}
func (dst *DanmakuElem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmakuElem.Merge(dst, src)
}
func (m *DanmakuElem) XXX_Size() int {
	return xxx_messageInfo_DanmakuElem.Size(m)
}
func (m *DanmakuElem) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmakuElem.DiscardUnknown(m)
}

var xxx_messageInfo_DanmakuElem proto.InternalMessageInfo

func (m *DanmakuElem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DanmakuElem) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *DanmakuElem) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *DanmakuElem) GetFontsize() int32 {
	if m != nil {
		return m.Fontsize
	}
	return 0
}

func (m *DanmakuElem) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *DanmakuElem) GetMidHash() string {
	if m != nil {
		return m.MidHash
	}
	return ""
}

func (m *DanmakuElem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DanmakuElem) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *DanmakuElem) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *DanmakuElem) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DanmakuElem) GetPool() int32 {
	if m != nil {
		return m.Pool
	}
	return 0
}

func (m *DanmakuElem) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func init() {
	proto.RegisterType((*DmSegMobileReply)(nil), "dm.DmSegMobileReply")
	proto.RegisterType((*DanmakuElem)(nil), "dm.DanmakuElem")
}

func init() { proto.RegisterFile("bilibili.proto", fileDescriptor_bilibili_95d7436dab1fa0ff) }

var fileDescriptor_bilibili_95d7436dab1fa0ff = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xfc, 0x30,
	0x14, 0xc4, 0x49, 0x77, 0xdb, 0xdd, 0x4d, 0xff, 0xff, 0x55, 0x82, 0xc8, 0xc3, 0x53, 0x59, 0x10,
	0x7a, 0xea, 0x41, 0x4f, 0xe2, 0x4d, 0x56, 0xf0, 0xe2, 0x25, 0x7b, 0xf3, 0xd6, 0x36, 0xcf, 0x6e,
	0x30, 0xe9, 0x2b, 0x6d, 0x44, 0xf4, 0xeb, 0xf8, 0x45, 0x25, 0x49, 0x57, 0x3c, 0x14, 0xde, 0x6f,
	0x66, 0x98, 0x0e, 0xe1, 0xdb, 0x46, 0x1b, 0xed, 0xbf, 0x6a, 0x18, 0xc9, 0x91, 0x48, 0x94, 0xdd,
	0xdd, 0xf1, 0xf3, 0xbd, 0x3d, 0x60, 0xf7, 0x4c, 0x8d, 0x36, 0x28, 0x71, 0x30, 0x9f, 0xe2, 0x9a,
	0xa7, 0x68, 0xd0, 0x4e, 0xc0, 0x8a, 0x45, 0x99, 0xdf, 0x9c, 0x55, 0xca, 0x56, 0xfb, 0xba, 0xb7,
	0xf5, 0xdb, 0xfb, 0xa3, 0x41, 0x2b, 0xa3, 0xbb, 0xfb, 0x4e, 0x78, 0xfe, 0x47, 0x16, 0x5b, 0x9e,
	0x68, 0x05, 0xac, 0x60, 0xe5, 0x42, 0x26, 0x5a, 0x89, 0x2b, 0xbe, 0x1e, 0x46, 0xea, 0x46, 0x9c,
	0x26, 0x48, 0x0a, 0x56, 0xa6, 0xf2, 0x97, 0x85, 0xe0, 0x4b, 0x4b, 0x0a, 0x61, 0x11, 0xf4, 0x70,
	0xfb, 0xfc, 0x2b, 0xf5, 0x6e, 0xd2, 0x5f, 0x08, 0xcb, 0x98, 0x3f, 0xb1, 0xb8, 0xe0, 0x69, 0x4b,
	0x86, 0x46, 0x48, 0x0b, 0x56, 0xfe, 0x97, 0x11, 0x04, 0xf0, 0x95, 0xd5, 0xea, 0xa9, 0x9e, 0x8e,
	0x90, 0x15, 0xac, 0xdc, 0xc8, 0x13, 0x7a, 0xa7, 0xa5, 0xde, 0x61, 0xef, 0x60, 0x15, 0x9d, 0x19,
	0x43, 0x93, 0xd3, 0x16, 0x61, 0x1d, 0x86, 0x46, 0x10, 0x97, 0x3c, 0xfb, 0x40, 0xdd, 0x1d, 0x1d,
	0x6c, 0xc2, 0x9f, 0x67, 0xf2, 0x7a, 0xdd, 0x3a, 0x4d, 0x3d, 0xf0, 0x50, 0x33, 0x93, 0xdf, 0x3f,
	0x10, 0x19, 0xc8, 0xe3, 0x7e, 0x7f, 0xfb, 0x66, 0xad, 0x0e, 0x6e, 0x84, 0x7f, 0x21, 0x1a, 0xe1,
	0x21, 0x7b, 0x59, 0x56, 0xf7, 0xca, 0x36, 0x59, 0x78, 0xf3, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x4e, 0x41, 0x28, 0x85, 0x01, 0x00, 0x00,
}
